### PR TITLE
add fix for colab plotting

### PR DESCRIPTION
**Pull request by rafmacalaba**
solves #89 
notebook: https://colab.research.google.com/drive/1TEJDLxlxSqDBghlJplbN2PWmktXpWPrI?usp=sharing

### CODE REVIEW

**Comment by enzoampil** [comment]
Your original colab checker actually looks better!

```
import sys
IN_COLAB = 'google.colab' in sys.modules
```

**Comment by rafmacalaba** [comment]
I just thought na mas simple yung try and except :) just tell me if you want that nalang instead of what was implemented.

**Comment by enzoampil** [comment]
Fair! Yeah ok let's go w/ the import. Think it might have less gotchas as well

**Comment by enzoampil** [comment]
@rafmacalaba can you do a rebase? I updated the backtrader version and requirements, and this it relates to the fix :)

**Comment by enzoampil** [comment]
Actually all good. I did another test, and this should be good to go!

**Comment by rafmacalaba** [comment]
I’ll check tomorrow Enzo! Sorry I already shutdown my laptop :<


Sent from Yahoo Mail for iPhone


On Saturday, May 30, 2020, 10:37 PM, Lorenzo Ampil <notifications@github.com> wrote:




Actually all good. I did another test, and this should be good to go!

**Comment by enzoampil** [comment]
@rafmacalaba all good already merged :)

**Pull request merged**
