### PR TITLE
Add periodic "income" feature to resolve #215

### LINKED ISSUE #215: Add cash during run?
How can I add cash every month during backtesting?

I'd like to backtest a strategy that looks like this:

1. Every month, another $1,000 is added in cash. Say, surplus from my salary. Let's call this "income".
2. While the algorithm does not buy any more stock, my income accumulates.
3. Once tha algorithm decides to buy stock, it will use...
a) all of the available cash on hand.
b) a pre-determined percentage of the cash on hand.
4. The algorithm never sells any stock (I think I can do that by setting upper_limit=999).

### PR DESCRIPTION
**Pull request by enzoampil**
### This PR allows users to set periodic increases to their cash balance by utilizing `add_cash_amount` and `add_cash_freq`

**Details**
1. **`add_cash_amount` indicates the amount of cash you want to add to your portfolio at each "add cash date".** Once this cash balance is added, the same `buy_prop` will be used as basis for guiding position sizing for now.
2. **`add_cash_freq` indicates the frequency that you add cash.** Currently you can choose from monthly ("M"), on the first day of the month, weekly ("W"), on Monday, or a custom cron notation that indicates your cadence of choice (e.g. 0 0 5 * * for montly on the fifth day of the week).
3. **In the case that the next add cash date lies on a day not contained in the input time series** (e.g. a weekend), the algo will assume the cash inflow is added on the earliest next date (e.g. if the add cash date is Nov 1 which is a weekend, Sunday, with no data, the cash is added on the next weekday, Nov 2, Monday.

### CODE REVIEW

**Review by jgendrinal — COMMENTED** [review]
Made a preliminary notebook [here](https://colab.research.google.com/drive/1aW3izFlNgexeSIWku9yJKuL2XzwTkf7I?usp=sharing). Looking good so far! 

Only high-level question I have @enzoampil is whether cron will be the way we do this longer-term moving forward. It might not be the most user-friendly way to do it, but then again, I can't think of an alternative haha

**Comment by enzoampil** [comment]
Thanks @jgendrinal! No the long term is to follow the freq approach similar to pandas datetime columns. For bow the only modes are monthly (M) and weekly (W). I plan to make this more easily configurable later so it can be set based on an arbitrary number of weeks and months, eg by preceding by a number in a generalizable way (eg 2W would indicate every 2 weeks). For now, we will have weekly and monthly, and cron is just there for those who want a way to perfectly configure the timing outside of monthly and weekly. 😃

**Comment by jgendrinal** [comment]
LGTM! :D

**Comment by enzoampil** [comment]
Thanks @jgendrinal will merge this now :smile:

**Comment by jpdeleon** [comment]
Two things: (1) please add the details in your PR description to the backtest docstring; (2) there is a `max` is type `dict` in `metrics` result in `backtest`.

**Comment by enzoampil** [comment]
@jpdeleon Thanks jerome, will fix these in a separate PR :smile:

**Comment by jgendrinal** [comment]
@jpdeleon @enzoampil I'll do docs alignment when I push stuff to the fastquant-docs repo

**Pull request merged**
