### PR TITLE
Disclosures

### PR DESCRIPTION
**Pull request by jpdeleon**
* added smart caching in ‘load_disclosures’ method
* added test_disclosures.py
* added batch download script

### CODE REVIEW

**Comment by jpdeleon** [comment]
To test smart caching, try instantiating `CompanyDIsclosures` with different `start_date` and `end_date` and make sure no data is downloaded twice and cache is only overwritten when necessary.

**Comment by enzoampil** [comment]
@jpdeleon  Keep getting the error below. Also shows up in the disclosure unit test.

PHISIX_SYMBOL = "JFC"
DATE_START = "2019-01-01"
DATE_END = "2019-04-12"

cd = CompanyDisclosures(
    symbol=PHISIX_SYMBOL, start_date=DATE_START, end_date=DATE_END
)
Pulling JFC disclosures summary...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-819df15e8f18> in <module>()
      4 
      5 cd = CompanyDisclosures(
----> 6     symbol=PHISIX_SYMBOL, start_date=DATE_START, end_date=DATE_END
      7 )
1 frames
/content/fastquant/fastquant/disclosures.py in get_company_disclosures(self)
    141         parsed_html = BeautifulSoup(html, "lxml")
    142         table = parsed_html.find("table", {"class": "list"})
--> 143         table_rows = table.find_all("tr")
    144         lines = []
    145         edge_nos = []
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by enzoampil** [comment]
@jpdeleon Can you also resolve the remaining errors on Travis CI? :)

https://travis-ci.com/github/enzoampil/fastquant/builds/159965937

**Comment by enzoampil** [comment]
@jpdeleon If I query the same date range for the same company twice, I shouldn't see a loading screen for the second one correct? It seems to still be pulling twice from the same arguments.
```
from fastquant import *

PHISIX_SYMBOL = "JFC"
DATE_START = "01-01-2019"
DATE_END = "04-12-2019"

cd = CompanyDisclosures(
    symbol=PHISIX_SYMBOL, start_date=DATE_START, end_date=DATE_END
)
# 100%|██████████| 6/6 [00:04<00:00,  1.22it/s]

# Test if caching works
# Looks like it doesn't work since a loading screen still appears
cd = CompanyDisclosures(
    symbol=PHISIX_SYMBOL, start_date=DATE_START, end_date=DATE_END
)
# 100%|██████████| 6/6 [00:04<00:00,  1.26it/s]
```

**Comment by jpdeleon** [comment]
@enzoampil You will always see the loading screen because the disclosures data goes inside for loop with tqdm either it is a new query or loading cache. Your query loads the cache in both instances above and so the loading time is the same. It takes significantly longer if you query new data, so try the same test above but using another symbol in the same date range. The difference between the first and second query should be more than 30 seconds. Then change the start_date say one month earlier and you should see it will load cache and download only the unavailable disclosures.

**Comment by jpdeleon** [comment]
@enzoampil can you check why this method returns empty html?

https://github.com/enzoampil/fastquant/blob/9a905e46e3e8d0809aa0f51145e60472650e673c/fastquant/disclosures.py#L584

It's the same function migrated from fastquant.py.

**Comment by enzoampil** [comment]
Thanks, can confirm that overlapping queries are only saving results for the unqueried dates, based on runtime. Querying from 1 month, to 2 month, to 3 month periods (with overlapping dates), gives similar runtimes using %%time.

**Pull request merged**
