### PR TITLE
refactor get-stock-data to default in yf

### LINKED ISSUE #235: [FEATURE] Make yahoo finance the default for get_stock_data
With our new direction of prioritizing more generally usable features, I think it makes sense to make `get_stock_data` default to yahoo finance instead of pse. So make the logic so that if the ticker is not detected in yahoo finance, only then does it query for PSE.

Also, given this change, I think the best format would be the standard `OHLCV`. If it resorts to `phisix` we just bring it back to `C` format.

cc @jpdeleon @jgendrinal in case you have thoughts on this

### PR DESCRIPTION
**Pull request by rafmacalaba**
just refactored get_stock_data to default in yahoo finance.

default format for yahoo data is `ohlcv` and if the ticker is not found in yf it goes to phisix with format of `c`

closes #235

### CODE REVIEW

**Review by jpdeleon — COMMENTED** [review]
Can't review in detail but I noticed network.py might not work because it assumes data is taken from PSE. If we generalize it to yf, then it needs to get sector and sub-sector information.

**Comment by rafmacalaba** [comment]
@jpdeleon thanks for this info jerome :D. @enzoampil isn't this handled by the test `python/tests/test_network.py` ?

**Comment by enzoampil** [comment]
@rafmacalaba Yes, the test looks like its passing, and we're not excluding the PSE pipeline, we're just running Yahoo finance first, and the PSE after if the ticker was not found. There might be naming overlaps, but that's likely an edge case and I'm okay addressing this in a future PR if bugs come up.

**Review by enzoampil — APPROVED** [review]
LGTM. Thanks for taking this on @rafmacalaba :smile:

Great work as usual!

**Pull request merged**
