### PR TITLE
Multi strategy V1

### PR DESCRIPTION
**Pull request by enzoampil**
### This PR implements multi strategy support and (partially) resolves issue #113.

With this PR, multiple registered strategies can be utilized together in an **OR** fashion, where buy or sell signals are applied when at least one of the strategies trigger them.

#### How to use

The above can be implemented by setting `strategy="multi"` in the `backtest` function, and setting a new `strats` parameter as a dictionary where the keys are the strategy aliases (e.g. `smac`), and the values are the parameter dictionaries for each strategy.

Also, auto grid search should work normally by passing in parameter values as a list. Lastly, you'll see that the column names corresponding to parameters will be mapped to a specific strategy alias to avoid duplicate column names for common parameters (e.g. `smac.fast_period`).

*Note: plotting is not yet supported since multi-strategy plotting isn't a built in functionality for backtrader. We can add this later in a separate PR if we deem it worth the effort.*

#### Sample usage

You can try these out yourself on this colab [notebook](https://colab.research.google.com/drive/1PjzTR-76EPM6baZNuwDNNCegpLKXCOXX?usp=sharing).

```
from fastquant import backtest, get_stock_data
df = get_stock_data("JFC", "2018-01-01", "2019-01-01")

# Utilize single set of parameters
strats = { 
    "smac": {"fast_period": 35, "slow_period": 50}, 
    "rsi": {"rsi_lower": 30, "rsi_upper": 70} 
} 
res = backtest("multi", df, strats=strats)
res.shape
# (1, 16)


# Utilize auto grid search
strats_opt = { 
    "smac": {"fast_period": 35, "slow_period": [40, 50]}, 
    "rsi": {"rsi_lower": [15, 30], "rsi_upper": 70} 
} 

res_opt = backtest("multi", df, strats=strats_opt)
res_opt.shape
# (4, 16)
```

@jpdeleon @rafmacalaba keen to get your feedback on this!

### CODE REVIEW

**Comment by jpdeleon** [comment]
Short but sweet! All my tests passed! Raf can merge after.

**Comment by enzoampil** [comment]
@jpdeleon Added to tests!

**Comment by rafmacalaba** [comment]
@enzoampil @jpdeleon lgtm! Congrats enzo!

**Comment by enzoampil** [comment]
thanks! merging now :)

**Pull request merged**
