### PR TITLE
Revise github actions

### LINKED ISSUE #288: [FEATURE] Link to fastquant-docs
Create a link to the fastquant-docs [repo](https://github.com/fastquant-org/fastquant-docs)

### PR DESCRIPTION
**Pull request by jgendrinal**
Resolves #288

### CODE REVIEW

**Comment by jgendrinal** [comment]
@enzoampil, will edit the workflow on your signal :) thanks!

**Comment by enzoampil** [comment]
@jgendrinal what's causing the failing build? :smile:

**Comment by jgendrinal** [comment]
@enzoampil github actions build has a separate check as well. still need to edit the workflow to use my PAT for the run. let me know if you've added it already to the repository secrets

**Comment by jgendrinal** [comment]
DO NOT MERGE

**Comment by jgendrinal** [comment]
Temporarily closing PR to focus on docs

**Pull request closed without merging**
