### PR TITLE
[WIP] Auto grid search

### PR DESCRIPTION
**Pull request by enzoampil**
### This PR applies auto grid search with the `backtest` function and resolves issue #75.

The following are applied:

1. Perform grid search if any of the parameters are input as a non-string`iterable`
2. Add explicit usage of `Analyzers` to choose the metric of comparison across strategies
3. Will set [returns](https://github.com/mementum/backtrader/blob/master/backtrader/analyzers/returns.py) and [sharpe](https://github.com/mementum/backtrader/blob/master/backtrader/analyzers/sharpe.py) as the default analyzers, while also including profit & loss (`pnl`) as a metric.
4. Instead of `cerebro`, `parameters` and `metrics` will be returned by backtest as `pd.DataFrame`. These are sorted based on `sort_by` (desc) which is the normalized return by default (`rnorm`). These come from `stratruns`, since this contains both analyzer metrics and all metrics related to the run (e.g. final portfolio value)
5. Apply regular plotting with one set of parameters (no arguments with multiple values). If multiple parameter combinations are run (requiring a grid search), the **optimal parameters** (based on `sort_by` metric) are backtested again an plotted at the end.
6. Remove `__main__` since comprehensive tests are already contained in `test_strategies.py`

@jpdeleon You can test it with the code snippet below:

```
from fastquant import *
params, metrics = backtest("smac", DATA_FILE, fast_period=[6,7,8,9,10], slow_period=[40, 45, 50], verbose=False, plot=True)

===Global level arguments===
init_cash : 100000
buy_prop : 1
sell_prop : 1
===Strategy level arguments===
fast_period : 6
slow_period : 40
Final PnL: -991.81
...
```

Can also run it from Colab [here](https://colab.research.google.com/drive/1T2s9HTCJoIjN7QTFJljZDRaDMkuKKyZb?usp=sharing)

### CODE REVIEW

**Comment by jpdeleon** [comment]
Looks awesome. Will test in a bit.

**Comment by enzoampil** [comment]
@jpdeleon Update: pushed a new commit where if `plot==True` with multiple parameter combinations, a plot is still generated, but only for the **optimal parameters**.

The optimal parameters (top 1) are also printed at the end of the grid search

**Comment by jpdeleon** [comment]
Tried the following:
```python
from fastquant import backtest, DATA_FILE

params, metrics = backtest("smac", 
                           DATA_FILE, 
                           fast_period=[6,7,8,9,10], 
                           slow_period=[40, 45, 50], 
                           verbose=False, 
                           plot=True
                          )
```
which throwed this error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a0820e7c1b67> in <module>
      1 from fastquant import backtest, DATA_FILE
      2 
----> 3 params, metrics = backtest("smac", 
      4                            DATA_FILE,
      5                            fast_period=[6,7,8,9,10],

~/github/research/project/fastquant/fastquant/strategies.py in backtest(strategy, data, commission, init_cash, data_format, plot, verbose, **kwargs)
    530     if verbose:
    531         print("Starting Portfolio Value: %.2f" % cerebro.broker.getvalue())
--> 532     cerebro.run()
    533     if verbose:
    534         print("Final Portfolio Value: %.2f" % cerebro.broker.getvalue())

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/cerebro.py in run(self, **kwargs)
   1125             # let's skip process "spawning"
   1126             for iterstrat in iterstrats:
-> 1127                 runstrat = self.runstrategies(iterstrat)
   1128                 self.runstrats.append(runstrat)
   1129                 if self._dooptimize:

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/cerebro.py in runstrategies(self, iterstrat, predata)
   1215             sargs = self.datas + list(sargs)
   1216             try:
-> 1217                 strat = stratcls(*sargs, **skwargs)
   1218             except bt.errors.StrategySkipError:
   1219                 continue  # do not add strategy to the mix

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in __call__(cls, *args, **kwargs)
     86         _obj, args, kwargs = cls.donew(*args, **kwargs)
     87         _obj, args, kwargs = cls.dopreinit(_obj, *args, **kwargs)
---> 88         _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
     89         _obj, args, kwargs = cls.dopostinit(_obj, *args, **kwargs)
     90         return _obj

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in doinit(cls, _obj, *args, **kwargs)
     76 
     77     def doinit(cls, _obj, *args, **kwargs):
---> 78         _obj.__init__(*args, **kwargs)
     79         return _obj, args, kwargs
     80 

~/github/research/project/fastquant/fastquant/strategies.py in __init__(self)
    309         print("fast_period :", self.fast_period)
    310         print("slow_period :", self.slow_period)
--> 311         sma_fast = bt.ind.SMA(period=self.fast_period)  # fast moving average
    312         sma_slow = bt.ind.SMA(period=self.slow_period)  # slow moving average
    313         self.crossover = bt.ind.CrossOver(

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/indicator.py in __call__(cls, *args, **kwargs)
     51     def __call__(cls, *args, **kwargs):
     52         if not cls._icacheuse:
---> 53             return super(MetaIndicator, cls).__call__(*args, **kwargs)
     54 
     55         # implement a cache to avoid duplicating lines actions

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in __call__(cls, *args, **kwargs)
     86         _obj, args, kwargs = cls.donew(*args, **kwargs)
     87         _obj, args, kwargs = cls.dopreinit(_obj, *args, **kwargs)
---> 88         _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
     89         _obj, args, kwargs = cls.dopostinit(_obj, *args, **kwargs)
     90         return _obj

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in doinit(cls, _obj, *args, **kwargs)
     76 
     77     def doinit(cls, _obj, *args, **kwargs):
---> 78         _obj.__init__(*args, **kwargs)
     79         return _obj, args, kwargs
     80 

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/indicators/sma.py in __init__(self)
     41         # Before super to ensure mixins (right-hand side in subclassing)
     42         # can see the assignment operation and operate on the line
---> 43         self.lines[0] = Average(self.data, period=self.p.period)
     44 
     45         super(MovingAverageSimple, self).__init__()

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/indicator.py in __call__(cls, *args, **kwargs)
     51     def __call__(cls, *args, **kwargs):
     52         if not cls._icacheuse:
---> 53             return super(MetaIndicator, cls).__call__(*args, **kwargs)
     54 
     55         # implement a cache to avoid duplicating lines actions

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in __call__(cls, *args, **kwargs)
     86         _obj, args, kwargs = cls.donew(*args, **kwargs)
     87         _obj, args, kwargs = cls.dopreinit(_obj, *args, **kwargs)
---> 88         _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
     89         _obj, args, kwargs = cls.dopostinit(_obj, *args, **kwargs)
     90         return _obj

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/metabase.py in doinit(cls, _obj, *args, **kwargs)
     76 
     77     def doinit(cls, _obj, *args, **kwargs):
---> 78         _obj.__init__(*args, **kwargs)
     79         return _obj, args, kwargs
     80 

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/indicators/basicops.py in __init__(self)
     42     def __init__(self):
     43         super(PeriodN, self).__init__()
---> 44         self.addminperiod(self.p.period)
     45 
     46 

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/lineroot.py in addminperiod(self, minperiod)
    318         # pass it down to the lines
    319         for line in self.lines:
--> 320             line.addminperiod(minperiod)
    321 
    322     def incminperiod(self, minperiod):

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/lineroot.py in addminperiod(self, minperiod)
    351         Add the minperiod (substracting the overlapping 1 minimum period)
    352         '''
--> 353         self._minperiod += minperiod - 1
    354 
    355     def incminperiod(self, minperiod):

TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

**Comment by jpdeleon** [comment]
I encountered this bug:
```python
from fastquant import backtest, DATA_FILE

params, metrics = backtest("smac", 
                           DATA_FILE, 
                           fast_period=[5], 
                           slow_period=[40], 
                           verbose=False, 
                           plot=True,
                           #iplot=False #<------ can you add as kwarg
                          )
```

```python
===Global level arguments===
init_cash : 100000
buy_prop : 1
sell_prop : 1
===Strategy level arguments===
fast_period : 5
slow_period : 40
Final PnL: 4074.75
Time used (seconds): 0.0586695671081543
Optimal parameters: {'init_cash': 100000, 'buy_prop': 1, 'sell_prop': 1, 'execution_type': 'close', 'fast_period': 5, 'slow_period': 40}
Optimal metrics: {'rtot': 0.03993922419315939, 'ravg': 0.00015975689677263756, 'rnorm': 0.04108010631836676, 'rnorm100': 4.1080106318366765, 'sharperatio': 0.2137407382796959, 'pnl': 4074.75}

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-75f1a17c6bf0> in <module>
      1 from fastquant import backtest, DATA_FILE
      2 
----> 3 params, metrics = backtest("smac", 
      4                            DATA_FILE,
      5                            fast_period=[5],

~/github/research/project/fastquant/fastquant/strategies.py in backtest(strategy, data, commission, init_cash, data_format, plot, verbose, sort_by, **kwargs)
    625         # Plot only with the optimal parameters when multiple strategy runs are required
    626         if params_df.shape[0] == 1:
--> 627             cerebro.plot(figsize=(30, 15))
    628         else:
    629             print("=============================================")

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/cerebro.py in plot(self, plotter, numfigs, iplot, start, end, width, height, dpi, tight, use, **kwargs)
    987         for stratlist in self.runstrats:
    988             for si, strat in enumerate(stratlist):
--> 989                 rfig = plotter.plot(strat, figid=si * 100,
    990                                     numfigs=numfigs, iplot=iplot,
    991                                     start=start, end=end, use=use)

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/plot/plot.py in plot(self, strategy, figid, numfigs, iplot, start, end, **kwargs)
    218                         downinds=self.dplotsdown[ind])
    219 
--> 220                 self.plotdata(data, self.dplotsover[data])
    221 
    222                 for ind in self.dplotsdown[data]:

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/plot/plot.py in plotdata(self, data, indicators)
    666         axdatamaster = None
    667         if self.pinf.sch.volume and voloverlay:
--> 668             volplot = self.plotvolume(
    669                 data, opens, highs, lows, closes, volumes, vollabel)
    670             axvol = self.pinf.daxis[data.volume]

~/miniconda3/envs/quant/lib/python3.8/site-packages/backtrader/plot/plot.py in plotvolume(self, data, opens, highs, lows, closes, volumes, label)
    609 
    610                 volylim /= self.pinf.sch.volscaling
--> 611                 ax.set_ylim(0, volylim, auto=True)
    612             else:
    613                 # plot a legend

~/miniconda3/envs/quant/lib/python3.8/site-packages/matplotlib/axes/_base.py in set_ylim(self, bottom, top, emit, auto, ymin, ymax)
   3621         self._process_unit_info(ydata=(bottom, top))
   3622         bottom = self._validate_converted_limits(bottom, self.convert_yunits)
-> 3623         top = self._validate_converted_limits(top, self.convert_yunits)
   3624 
   3625         old_bottom, old_top = self.get_ylim()

~/miniconda3/envs/quant/lib/python3.8/site-packages/matplotlib/axes/_base.py in _validate_converted_limits(self, limit, convert)
   3156             if (isinstance(converted_limit, Real)
   3157                     and not np.isfinite(converted_limit)):
-> 3158                 raise ValueError("Axis limits cannot be NaN or Inf")
   3159             return converted_limit
   3160 

ValueError: Axis limits cannot be NaN or Inf
```

image

**Comment by enzoampil** [comment]
@jpdeleon Thanks for showing this. I also just noticed this now ... The plotting of `backtrader` has always been problematic. I'm on it!

Honestly tempted to send a PR to `backtrader` to make this more widely usable haha (currently not usable from Colab either).

**Comment by enzoampil** [comment]
Okay found a related issue in the backtrader docs [here](https://community.backtrader.com/topic/689/plotting-error-axis-limits-cannot-be-nan-or-inf/3)

**Pull request merged**
