### PR TITLE
add upperband lowerband to rsi indicator

### PR DESCRIPTION
**Pull request by khuyentran1401**
### Description

Allow users to customize `upperband` and `lowerband` when using rsi strategy.

### Checklist
 - [x] I am making a pull request from a branch other than master
 - [x] I have read the CONTRIBUTING.md
 - [x] I have added/edited documentation in a relevant docs/docusaurus markdown file
 - [x] (For new docs, check if not applicable) I have added the id of a new docs md to the docs/docusaurus/sidebars.js file

### CODE REVIEW

**Comment by khuyentran1401** [comment]
This is just a small change. I know you're on break so don't feel pressured to check it right away

**Review by jbdelmundo — APPROVED** [review]
I haven't noticed that the upper and lower limits are not being used in the indicator. Great!

**Review by enzoampil — APPROVED** [review]
Thanks for this @khuyentran1401 ! :smile:

**Comment by khuyentran1401** [comment]
Thank you for merging my pull requests!

**Pull request merged**
