### PR TITLE
WIP: Refactor structure

### PR DESCRIPTION
**Pull request by jbdelmundo**
Code refactoring:

- Separate files for each disclosure source
- Separate files for each strategy
- Separate files for each custom indicator
- Separate files for each data category( PSE/Stocks, Crypto, Forex)
- Separate file for backtesting wrapper `backtest()` for Backtrader

### CODE REVIEW

**Comment by enzoampil** [comment]
@jpdeleon @rafmacalaba Can I get your eyes on this one? :)

**Comment by rafmacalaba** [comment]
@enzoampil sure

**Comment by enzoampil** [comment]
@jbdelmundo Had an initial look but looks okay so far :smile:

Can we start with making sure that our formatting follows [black](https://github.com/psf/black) for each of the modules?

`black <file_name>.py`

**Comment by rafmacalaba** [comment]
looks good! my feedback was only the imports are not working in the CI build. @jbdelmundo

**Comment by enzoampil** [comment]
@jbdelmundo lemme know if you need assistance with the requested changes :) Was hoping to get this merged before applying additional fixes to the code base so that rebasing won't be a nightmare haha

**Comment by jbdelmundo** [comment]
Will repoen PR with another branch

**Pull request closed without merging**
