### PR TITLE
refactor sentiment strat

### PR DESCRIPTION
**Pull request by rafmacalaba**
This PR Generalizes the `SentimentStrategy` to be compatible with Disclosures and Twitter
Notable Changes in the repo:
`strategies.py`
added a Custom `SentimentDF` class which extends `PandasData` datafeed to have `sentiment_score` column which can then be accessed inside via `self.data.sentiment_score`
changed `get_bt_news` to `get_bt_news_sentiment` to make it more transparent to the user.

more info in collab [link](https://colab.research.google.com/drive/1ahl0o7BBR1ULhM8e6blcSt7_BniFnTXb?usp=sharing)

### CODE REVIEW

**Comment by jpdeleon** [comment]
LGTM! I'll try to fix plotting format issue to use "default" in a separate PR for disclosures.

**Comment by rafmacalaba** [comment]
> LGTM! I'll try to fix plotting format issue to use "default" in a separate PR for disclosures.

Cool! Please approve changes to be merged :D

**Comment by enzoampil** [comment]
Awesome stuff @rafmacalaba !

**Comment by rafmacalaba** [comment]
> Awesome stuff @rafmacalaba !

Thanks @enzoampil ! was merged earlier by jerome. feel free to revert/add comments/changes.

**Comment by enzoampil** [comment]
Nah LGTM, great job!

**Pull request merged**
