### PR TITLE
Update portfolio notebook

### PR DESCRIPTION
**Pull request by benjcabalona1029**
Issue: [177](https://github.com/enzoampil/fastquant/issues/177) 

Updates made : 

- Use fastquant `Portfolio` class
- Added an interactive chart implemented in altair

### CODE REVIEW

**Comment by benjcabalona1029** [comment]
For review @enzoampil  @jpdeleon

**Comment by jpdeleon** [comment]
LGTM!

I like how you emphasized how easy to do it in fastquant:
```
from fastquant import Portfolio
p = Portfolio(stock_list,"2017-01-01", "2020-01-01")
fig = p.plot_portfolio(N=1000)
```
I guess we are keeping the "do it in 3 lines" pitch!

**Comment by enzoampil** [comment]
@benjcabalona1029 was thinking for the title subtitles how about something like:

**Title:** Implement Markowitz Portfolio Optimization in Only 3 Lines of Code
**Subtitle:** Use fastquant to maximizing the returns of your stock portfolio given its overall risk profile

**Comment by benjcabalona1029** [comment]
@enzoampil That works for me too it's similar to the technical tutorials that we already have [here.](https://enzoampil.github.io/fastquant-blog/)

**Comment by enzoampil** [comment]
LGTM :smile:

**Pull request merged**
