### PR TITLE
Backtesting functionality in R support

### LINKED ISSUE #141: [FEATURE] R support for backtesting
Will port R to python installation using the `reticulate` package

### PR DESCRIPTION
**Pull request by jgendrinal**
Resolve #141 

Attempts in this PR aim to import all trading strategies and the main `backtest` function the so that both R and Python have full support for them. Two approaches are top of mind. No. 1 will apply in this pull request:

**1. Use the `{reticulate}` package to port Python functionality into R**
Advantage - Relies on the backtrader framework
Disadvantage - Dependency on the latest PyPI release of fastquant

**2. Write native R code**
Advantage - Full control of the R functionality
Disadvantage - Rewriting something that can replace the backtrader from scratch

It is possible that we could implement No. 2 in a future PR.

### CODE REVIEW

**Comment by jgendrinal** [comment]
First challenge will be calling the right Python environment into R. Am thinking of starting it out with the following steps:

1. Find fastquant-env virtual environment, if does not exist, create it
2. Install fastquant repo from source into temporary directory (one-time)
3. Check if dependencies match, if not, install missing or updated versions
4. Install fastquant 
5. Call fastquant module into R environment

**Comment by jgendrinal** [comment]
Will write tests for these tomorrow (bad practice, I know)

**Comment by jgendrinal** [comment]
Build failed: I need to specify a python installation in Travis CI so that R can port to Python

**Comment by jgendrinal** [comment]
@enzoampil  @jpdeleon, Python is successfully ported to R. Need help understanding the `backtest` function and the different strategies. Hope to have a session for this next week. Thanks!

**Comment by enzoampil** [comment]
@jgendrinal Awesome, great progress. Let's discuss in the coming meetup :smile:

**Comment by jgendrinal** [comment]
Made the package much easier to load. Next set of improvements:
1. Set Travis CI to fail on warnings and errors (necessary for submission to CRAN). 
2. High-level function for backtest function. 
3. More documentation and testing.

**Comment by jgendrinal** [comment]
Controlled I/O. Will fine-tune this soon. Also plan to create new R functions for the plot and history functions.

**Comment by jgendrinal** [comment]
Will create new methods for plotting by creating a new 
`summary.backtest` and
`plot.backtest`
functions. 

R does not take verbose behavior too kindly in notebooks.

**Comment by enzoampil** [comment]
@jgendrinal is the new plotting functionality necessary to get it to work initially?

**Comment by jgendrinal** [comment]
Oh, not really. But the value of the backtest is that we get to see the history and the plot in a notebook. I've turned them both off by default.

**Comment by jgendrinal** [comment]
Sunsetting support for this temporarily as per #281

**Pull request closed without merging**
