### PR TITLE
Include backtrader indicators to fastquant via import

### PR DESCRIPTION
**Pull request by jbdelmundo**
Needed insights whether to just use `import *` to include everything (at a slight cost of loading all indicators) or import them individually (and probably to avoid class name conflicts)

### CODE REVIEW

**Comment by enzoampil** [comment]
@jbdelmundo Actually, I think I'd rather have peeps import them deliberately :) backtrader library is huge and I'd rather be intentional about which indicators we use :smile:

**Comment by jpdeleon** [comment]
@enzoampil @jbdelmundo  So I guess we do not need this PR anymore if we will keep the current import settings? Can we close?

**Comment by enzoampil** [comment]
Don't mind closing unless @jbdelmundo has another proposed approach that doesn't involve importing all the backtrader strats? :grin:

**Comment by jpdeleon** [comment]
Will close this for now.

**Pull request closed without merging**
